CREATE DATABASE IF NOT EXISTS Login;

USE Login;

CREATE TABLE usuario (
	
    id INT(11) NOT NULL AUTO_INCREMENT,
    rfc8 VARCHAR(8) DEFAULT NULL,
    admi VARCHAR(50) DEFAULT NULL,
    problema VARCHAR(50) DEFAULT NULL,
    descri VARCHAR(250) DEFAULT NULL,
    PRIMARY KEY(id)
);

DESCRIBE Login;
